import os
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from states.doc_state import DocState
from states.loader import Loader as load_node
from states.indexer import build_index as index_node
from states.summarizer import Summarizer as summary_node
from states.visualizer import Visualizer as visuals_node
from model.model import model1
from backend.sql_graph import sql_graph
import logging
logger=logging.getLogger(__name__)


# --- Tools Definition ---

def rag_tool(query: str, state: DocState):
    """Deep semantic search tool. Use this for specific questions about document content."""
    if not state.index:
        return "No document index available. Please enable RAG mode."
    
    retriever = state.index.as_retriever(similarity_top_k=3)
    nodes = retriever.retrieve(query)
    context = "\n".join([n.text for n in nodes])
    
    # Fallback: If RAG finds nothing, provide the general summary
    if not context or len(context) < 50:
        return f"Specific context not found. Using General Summary:\n{state.summary}"
        
    return f"Found Context:\n{context}"

def visualizer_tool(user_request: str, state: DocState):
    """Generates charts and graphs. Use this when the user asks for visuals, insights, or plots."""
    from states.visualizer import Visualizer
    updated_state = Visualizer(state, user_request)
    num_charts = len(updated_state.visuals.get('charts', []))
    if num_charts > 0:
        return f"SUCCESS: Generated {num_charts} charts/graphs based on the user's request: '{user_request}'. The visuals are stored in {state.folder_path}/visuals."
    else:
        return "NOTICE: Attempted to generate visuals but found no suitable data (tables or text). No charts were created."

analysis_tools = [rag_tool, visualizer_tool]

# --- 4. Node Definitions ---

def intent_node(state: DocState):

    logger.info("Intent Node: %s", state.user_query)
    """Automatically detects if the user needs RAG based on the query."""
    query = state.user_query.lower().strip()
    
    # Simple rule-based intent detection
    # If query is empty or just asking for a summary, use summary mode
    summary_keywords = ["summarize", "overview", "what is this", "summary", "tl;dr"]
    
    if not query or any(kw in query for kw in summary_keywords):
        state.use_rag = False
    else:
        # If it's a specific question, enable RAG
        state.use_rag = True
        
    return state

def chat_node(state: DocState):
    """Agent node that processes messages and decides tools/visuals."""
    
    # System message with explicit instructions for visualization
    # Dynamic System Message based on context
    num_charts = len(state.visuals.get('charts', [])) if state.visuals else 0
    has_sql_data = state.data_head or state.sql

    if has_sql_data:
        # SQL/Structured Data Context
        if num_charts > 0:
            # Charts exist -> Confirm projection
            instructions = (
                "1. The SQL Engine has ALREADY processed the data and generated visuals.\n"
                "2. Visuals are AUTOMATICALLY projected to the 'Evidence Nexus' on the dashboard.\n"
                "3. Do NOT ask the user if they want to see the chart. Simply confirm: 'Visuals have been projected to your dashboard.'\n"
                "4. ALWAYS include the text summary/list from 'Analytical Finding' (below) if the user asked for a list, counts, or specific details.\n"
                "5. If 'Analytical Finding' contains an error, report it directly to the user."
            )
        else:
            # SQL ran but NO charts (likely just a list/text request)
            instructions = (
                "1. The SQL Engine has processed the data.\n"
                "2. Report the 'Analytical Finding' (text/list) directly to the user.\n"
                "3. Do NOT mention 'visuals projected' if no new charts were created.\n"
                "4. If 'Analytical Finding' contains an error, report it."
            )
    else:
        # Unstructured/RAG Context
        instructions = (
            "1. STRICT RULE: If the user asks for a chart, plan, timeline, or visual, YOU MUST CALL 'visualizer_tool' immediately.\n"
            "2. Visuals generated by the tool will AUTOMATICALLY appear in the user's dashboard.\n"
            "3. Use 'rag_tool' to find context if needed, but ALWAYS trigger the visualizer for chart requests."
        )

    # System message with explicit instructions for visualization
    system_msg = SystemMessage(content=(
        f"You are DocSense AI, a document analysis expert.\n"
        f"SESSION: {state.folder_path} | FILE: {state.filename}\n"
        f"STATE:\n"
        f"- Summary: {state.summary or 'Not generated'}\n"
        f"- Tables: {len(state.extracted_tables)}\n"
        f"- Current Visuals: {len(state.visuals.get('charts', []))}\n"
        f"- SQL Data Head: {state.data_head or 'None'}\n"
        f"- Analytical Finding: {state.rag_response or 'None'}\n\n"
        f"INSTRUCTIONS:\n"
        f"{instructions}"
    ))
    
    messages = [system_msg] + state.messages
    if not any(isinstance(m, HumanMessage) for m in state.messages):
        query = state.user_query or "Summarize the document."
        messages.append(HumanMessage(content=query))

    # Dynamic Tool Binding
    current_tools = analysis_tools
    if state.data_head or state.sql:
        # In SQL mode, disable RAG tool to prevent "No index" errors
        current_tools = [visualizer_tool]

    model_with_tools = model1.bind_tools(current_tools)
    response = model_with_tools.invoke(messages)
    
    # Bridge to rag_response for frontend
    if not response.tool_calls:
        state.rag_response = response.content

    if not state.messages:
        return {"messages": [HumanMessage(content=state.user_query or "Summarize"), response], "rag_response": state.rag_response}
    return {"messages": [response], "rag_response": state.rag_response}


def sync_state(state: DocState):
    """Sync tool outputs or agent responses back to DocState fields."""
    if state.messages:
        last_msg = state.messages[-1]
        if isinstance(last_msg, AIMessage) and not last_msg.tool_calls:
            state.rag_response = last_msg.content
    return state

# --- 5. Router Logic ---

def manual_condition(state: DocState):
    last_message = state.messages[-1]
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tools"
    return END

def pipeline_router(state: DocState):
    """Router from load: analytics (if CSV/Excel) or index (if RAG) or summary."""
    ext = os.path.splitext(state.filename)[1].lower()
    if ext in ['.csv', '.xlsx', '.xls']:
        return "sql_analytics"
    if state.use_rag:
        return "index"
    return "summary"

# --- 6. Graph Construction ---

graph = StateGraph(DocState)

def execute_tools(state: DocState):
    """Manually executes tools to ensure state injection works correctly."""
    last_message = state.messages[-1]
    if not isinstance(last_message, AIMessage) or not last_message.tool_calls:
        return state
        
    for tool_call in last_message.tool_calls:
        tool_name = tool_call["name"]
        args = tool_call["args"]
        
        output = "Tool Error: Unknown Tool"
        try:
            if tool_name == "rag_tool":
                output = rag_tool(args.get("query"), state)
            elif tool_name == "visualizer_tool":
                output = visualizer_tool(args.get("user_request"), state)
        except Exception as e:
            output = f"Tool Execution Failed: {str(e)}"
            
        # Append tool output to messages
        from langchain_core.messages import ToolMessage
        state.messages.append(ToolMessage(content=str(output), tool_call_id=tool_call["id"]))
        
    return state

graph.add_node("load", load_node)
graph.add_node("intent", intent_node)
graph.add_node("index", index_node)
graph.add_node("summary", summary_node)
graph.add_node("visuals", visuals_node)
graph.add_node("chat_node", chat_node)
graph.add_node("tools", execute_tools)
graph.add_node("sync", sync_state)

# Sub-graph Node
graph.add_node("sql_analytics", sql_graph)

graph.add_edge(START, "load")
graph.add_edge("load", "intent")

graph.add_conditional_edges(
    "intent", 
    pipeline_router, 
    {
        "sql_analytics": "sql_analytics",
        "index": "index", 
        "summary": "summary"
    }
)

# SQL Flow integration
graph.add_edge("sql_analytics", "chat_node")

# Normal Flow
graph.add_edge("index", "summary")
graph.add_edge("summary", "chat_node")

graph.add_conditional_edges("chat_node", manual_condition, {"tools": "tools", END: END})
graph.add_edge("tools", "sync")
graph.add_edge("sync", "chat_node")

app_graph = graph.compile(checkpointer=None)










